#!/bin/bash

echo -n "Sisestage ainepunktide arv: "
read ainepunktid

echo -n "Sisestage nädalate arv: "
read aeg

aeg=`echo "scale=1;78/10" | bc`
echo $aeg
aeg_ymarda=`echo "($aeg+0.9)/1" | bc`
echo $aeg_ymarda
